//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteHCS_2.HCS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WCFMensaje", Namespace="http://schemas.datacontract.org/2004/07/BNA.FU.HCS")]
    [System.SerializableAttribute()]
    public partial class WCFMensaje : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ContenidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Contenido {
            get {
                return this.ContenidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContenidoField, value) != true)) {
                    this.ContenidoField = value;
                    this.RaisePropertyChanged("Contenido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HCS.IConectorBrokerWCF")]
    public interface IConectorBrokerWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConectorBrokerWCF/EnviarRecibir", ReplyAction="http://tempuri.org/IConectorBrokerWCF/EnviarRecibirResponse")]
        ClienteHCS_2.HCS.WCFMensaje[] EnviarRecibir(ClienteHCS_2.HCS.WCFMensaje msgMensaje, string strDestino);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConectorBrokerWCF/EnviarRecibir", ReplyAction="http://tempuri.org/IConectorBrokerWCF/EnviarRecibirResponse")]
        System.Threading.Tasks.Task<ClienteHCS_2.HCS.WCFMensaje[]> EnviarRecibirAsync(ClienteHCS_2.HCS.WCFMensaje msgMensaje, string strDestino);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConectorBrokerWCFChannel : ClienteHCS_2.HCS.IConectorBrokerWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConectorBrokerWCFClient : System.ServiceModel.ClientBase<ClienteHCS_2.HCS.IConectorBrokerWCF>, ClienteHCS_2.HCS.IConectorBrokerWCF {
        
        public ConectorBrokerWCFClient() {
        }
        
        public ConectorBrokerWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConectorBrokerWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConectorBrokerWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConectorBrokerWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClienteHCS_2.HCS.WCFMensaje[] EnviarRecibir(ClienteHCS_2.HCS.WCFMensaje msgMensaje, string strDestino) {
            return base.Channel.EnviarRecibir(msgMensaje, strDestino);
        }
        
        public System.Threading.Tasks.Task<ClienteHCS_2.HCS.WCFMensaje[]> EnviarRecibirAsync(ClienteHCS_2.HCS.WCFMensaje msgMensaje, string strDestino) {
            return base.Channel.EnviarRecibirAsync(msgMensaje, strDestino);
        }
    }
}
